### ISSUE TITLE
[Question] What's the problem on android? 

### ISSUE THREAD

**Issue by radiegtya** [MichaelCereda/react-native-form-generator#10]
What is the problem when I am running this on android?

**Comment by MichaelCereda** [comment]
I focused my effortts on IOS, so there are some specific ios styles and components.

I'm planning to release the android version soon (i'm creating a cross platform project).

**Comment by radiegtya** [comment]
Cool, will wait for this working.

**Comment by jbrodriguez** [comment]
Hi @MichaelCereda , just checking ... are you still far along on the ios+android version ?

**Comment by MichaelCereda** [comment]
I'm still working on it because I'm very busy lately.
Actually the components should work also on android.. It's  the style that
needs to be changed.

**Comment by vinceprofeta** [comment]
@MichaelCereda whats the status on android?

**Comment by jbrodriguez** [comment]
it won't happen, just follow the guides

**Comment by MichaelCereda** [comment]
Hello, android it's happening .. the app i was working on had an unexpected delay and i had to postpone the release of the android version.
I'm working on it right now.... i'm thinking to publish a revamped version of this plugin, that will include android support this week.

I'm sorry for the delay, but i'm the only developer.

Ps: thanks for your interest

**Comment by MichaelCereda** [comment]
Please check 0.8 branch https://github.com/MichaelCereda/react-native-form-generator/tree/v0.8
I'm adding android support and a lot of refactoring

**Comment by MichaelCereda** [comment]
Please check the new release... i added android support with basic styling (overridable).
I'm actively working on the project and I'm going to release new versions soon.

**Comment by sators** [comment]
How do you override on Android?  `style` prop is not working...?
