### ISSUE TITLE
Android doesn't show the input when a label is provided

### ISSUE THREAD

**Issue by johncblandii** [MichaelCereda/react-native-form-generator#102]
You can see what happens when I hot reload the app with a `containerStyle` and without it.

Shows the text input but it isn't full width:
`<InputField ref='subject' label='Subject' containerStyle={{alignItems: 'flex-start'}} />`

Doesn't show the text input at all:
`<InputField ref='subject' label='Subject' />`

Using a `placeholder` does properly display the input, but only if there is no label provided. This is using the latest master version.

![gif](http://recordit.co/Y98kNZgyxV.gif)

**Comment by johncblandii** [comment]
Any thoughts, @MichaelCereda?

Also, ignore the stack trace in there. I hit save too quick at one point.

**Comment by jbrodriguez** [comment]
@johncblandii I was having the same issue.

Turns out npmjs doesn't have the latest code from master.

It's 6 months old and that threw me off for a while, had to go back to basics :)

I installed the latest commit from github and all the problems went away.

**Comment by MikeDabrowski** [comment]
Sorry, I'm bit new to this things. How to install it from github? Just copy paste files over those from npmj?

**Comment by johncblandii** [comment]
Hrmmm....I thought I had master in there, but guess not. We really do need to get proper releases going on this repo so we can read the release notes, etc.

The forms look like crap on Android vs iOS. I'll test this more later to see how this works out.

**Comment by jbrodriguez** [comment]
@johncblandii I hear you 👍 

@MikeDabrowski you can do

```bash
yarn add MichaelCereda/react-native-form-generator#1bebb69 
```

**Comment by MikeDabrowski** [comment]
@johncblandii 
Yeah they do look like crap on android. I like the default look so at first I went vanilla but gathering the data from it later is bit painful. If one could merge the two ... that'd be nice :D

@jbrodriguez 
Can I do it with npm? I don't have yarn on windows installed.

**Comment by jbrodriguez** [comment]
@MikeDabrowski it would be

```bash
npm install MichaelCereda/react-native-form-generator.git#1bebb69 
```

**Comment by MikeDabrowski** [comment]
Great thanks

**Comment by johncblandii** [comment]
Master does work so I'm going to consider this closed, but a proper release needs to be pushed.

**Comment by ababba15** [comment]
Same problem here. `npm install MichaelCereda/react-native-form-generator.git#1bebb69` didn't help.
