### ISSUE TITLE
How to set value on a field programmatically 

### ISSUE THREAD

**Issue by whippersnapper** [MichaelCereda/react-native-form-generator#16]
I'm trying to set value to a subsequent field based on onValueChange of another field. How would I go about doing that? I don't really see a way where the API expose that functionality? Thanks.

**Comment by MichaelCereda** [comment]
I would personally do that using the onchange at form level.
I'm going to attach an example

On Sun, Jun 26, 2016, 1:59 PM Ling <notifications@github.com> wrote:

> I'm trying to set value to a subsequent field based on onValueChange of
> another field. How would I go about doing that? I don't really see a way
> where the API expose that functionality? Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichaelCereda/react-native-form-generator/issues/16>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGjfvvsy1Q3X8ybClV1_Z8p3Ckb7RACks5qPmmlgaJpZM4I-inG>
> .
>
-- 
Michael Cereda
http://michaelcereda.com

**Comment by MichaelCereda** [comment]
check this example... 
https://github.com/MichaelCereda/react-native-form-generator/blob/form-validation/examples/FormView.js
as you can notice you can set a state at handleFormChange, so you can change your form as you prefer.

that branch works very well, but react has a strange bug with DatePickerIOS that I'm trying to fix

**Comment by seantempesta** [comment]
Also, FWIW, I created a pull request to allow easier access to value and to override the value on change. 

https://github.com/MichaelCereda/react-native-form-generator/pull/17

**Comment by whippersnapper** [comment]
@MichaelCereda Thanks for the reply. It seems that the onChange at the Form level does capture the form field data values. However, when I tried to manipulate the formData and update by setState, it doesn't update the render view for that specific form field. Is there something else that I'm missing?

**Comment by MichaelCereda** [comment]
... i'm working on that right now, i'm adding the "reset" feature and the possibility of directly manipulate form values.
I'm preparing the 0.9 release that will contain a lot of features, you can check it in the 0.9-beta branch

**Comment by MichaelCereda** [comment]
as in my prev comment now you can just do this

https://github.com/MichaelCereda/react-native-form-generator/blob/master/examples/FormView.js#L89
