### ISSUE TITLE
labelStyle does not make changes to label on InputField component

### ISSUE THREAD

**Issue by abrarmusa** [MichaelCereda/react-native-form-generator#18]

**Comment by MichaelCereda** [comment]
Can you attach a little code example? I'm trying to figure out what's wrong. 
Thank you

**Comment by MichaelCereda** [comment]
labelStyle works on inputCompoment it will be fixed in 0.9

**Comment by MichaelCereda** [comment]
Fixed and pushed in 0.8.2,
published also on npm.
Have a nice day

**Comment by abrarmusa** [comment]
Thank you !

**Comment by abrarmusa** [comment]
heres some sample code

<InputField ref='name'  containerStyle={{backgroundColor: '#0e0f24', borderBottomWidth: 1, borderBottomColor: '#999b9d'}}  style={{color:'white', fontSize: 14}} label='name:' labelStyle={{color: 'white', fontFamily: 'Cochin', fontSize: 10}}/>

**Comment by MichaelCereda** [comment]
does it work now?
