### ISSUE TITLE
You should add 'multiline' prop to InputField

### ISSUE THREAD

**Issue by melihmucuk** [MichaelCereda/react-native-form-generator#2]

**Comment by MichaelCereda** [comment]
ok.. i'm going to release the change right now... i'm actually allowing to pass every property down to the TextInput, to allow more control .

**Comment by melihmucuk** [comment]
Thanks !

**Comment by MichaelCereda** [comment]
Added multiline support

<InputField ref='first_name' multilline={true} label='First Name' placeholder='First Name'/>

please specify the height of the field, autoExpand is coming soon (with the next version of react-native!)
