### ISSUE TITLE
[Question] Modal DatePicker?

### ISSUE THREAD

**Issue by braco** [MichaelCereda/react-native-form-generator#20]
Great work! Thinking about ripping tcomb out and replacing it with yours.

What would be the best way to Modalize some components? For example, a date field that displays

MM/DD/YYYY

and when clicked, a full DatePicker comes up inside a Modal, not inline.

I assume this would necessitate a custom component; is there a clever way to extend without duplicating everything? I'm looking at your source now, but don't see a clear path to this goal.

edit: maybe a prop could replace this line in your new branch: https://github.com/MichaelCereda/react-native-form-generator/blob/0.9-beta/src/lib/DatePickerComponent.ios.js#L71 which would allow for a custom DatePicker view.

**Comment by MichaelCereda** [comment]
Hello, first of all thanks for using my project.
In 0.9 I'm working a lot on DatePicker Component to obtain more flexibilty.
I agree with you, changing that line should do the trick, at this point I can check if it's possible to have a custom wrapper for the DatePicker, so you can use a simple View, a Modal or a Custom component.

I'm going to add it to 0.9 ASAP.
thank you

**Comment by braco** [comment]
Cool, I'll hold off until your next push. Thanks!

**Comment by MichaelCereda** [comment]
changed pushed .. please check the example... pressing on setAlarm
