### ISSUE TITLE
DatePickerField Warning

### ISSUE THREAD

**Issue by tomelsner** [MichaelCereda/react-native-form-generator#21]
On ios, RN 27.2 the datepicker using the example code throws several warnings:

Warning: Failed propType: Invalid prop `date` of type `Number` supplied to `RCTDatePicker`, expected instance of `Date`. Check the render method of `DatePickerIOS`.

Warning: Failed propType: Required prop `onDateChange` was not specified in `RCTDatePicker`. Check the render method of `DatePickerIOS`.

Warning: Failed propType: Invalid prop `maximumDate` of type `Number` supplied to `RCTDatePicker`, expected instance of `Date`. Check the render method of `DatePickerIOS`.

Warning: Failed propType: Invalid prop `minimumDate` of type `Number` supplied to `RCTDatePicker`, expected instance of `Date`. Check the render method of `DatePickerIOS`.

**Comment by MichaelCereda** [comment]
Yes.. it was related to multiple RN bugs on DatePickerIOS, see:
https://github.com/facebook/react-native/issues/6264
https://github.com/facebook/react-native/issues/2397

You can hide them using the yellowbox flag, or update RN to 0.28 and get rid of the bugs.
Have a nice day.

**Comment by tomelsner** [comment]
Thank you!

**Comment by tomelsner** [comment]
Also having trouble importing the KeyboardAwareScrollView. Using
import { KeyboardAwareScrollView } from 'react-native-form-generator';
Just returns KeyboardAwareScrollView as undefined.

**Comment by MichaelCereda** [comment]
Yes.. Scrollview now has the scrollto method that in association with
onlayout can be used to scroll to the element.
KeyboardAwareScrollview was buggy and will be deleted in next version. (it
was created as workaround of a bug/lack of feature in react.)
I'm going to update the example to cover also tour user case.
Thank you.

On Thu, Jul 7, 2016, 2:32 PM tomelsner <notifications@github.com> wrote:

> Also having trouble importing the KeyboardAwareScrollView. Using
> import { KeyboardAwareScrollView } from 'react-native-form-generator';
> Just returns KeyboardAwareScrollView as undefined.
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/MichaelCereda/react-native-form-generator/issues/21#issuecomment-231064242>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGjflOAoHd3I4jqSU4CaxHU-etenjg4ks5qTPHjgaJpZM4JHAYF>
> .
>
-- 
Michael Cereda
http://michaelcereda.com
