### ISSUE TITLE
label Of Form not shown?

### ISSUE THREAD

**Issue by abellee** [MichaelCereda/react-native-form-generator#22]
I set the label of Form,
but It seems not work at all?

**Comment by MichaelCereda** [comment]
Yes, from 0.9 to give more flexibility i removed the standard Separator that was inside _Form_.
Just add a Separator inside your form and pass the text to the label prop.

Thank you for using my library

**Comment by abellee** [comment]
Actually, You've done a great work!! I should thank you to save my time.
and another problem is if I use the KeyboardAwareScrollView,
the Simulator will shows me an error:
![image](https://cloud.githubusercontent.com/assets/707615/16657808/5ea36c60-4496-11e6-8f23-6d56aab1a176.png)
Am I doing anything wrong?
and code is just:

    import React, { Component } from 'react';

    import {
        View,
        Text,
        ScrollView
    } from 'react-native';

    import {
        Form,
        Separator,
        InputField,
        KeyboardAwareScrollView
    } from "react-native-form-generator";

    class ShirtOrder extends Component {

        state={
            formData: {}
        }

        render(){
            return (
                <KeyboardAwareScrollView
                    ref="scroll"
                >

                </KeyboardAwareScrollView>
            );
        }
    }
    export default ShirtOrder;

**Comment by MichaelCereda** [comment]
yes.. that because _KeyboardAwareScrollView_ is not exported anymore
you can try to access it directly.
try something like   
```javascript
import {
    KeyboardAwareScrollView
} from "react-native-form-generator/src/KeyboardAwareScrollView";
```

or copy it from the repo.

**Comment by abellee** [comment]
also not working but import it from react-native-keyboard-aware-scroll-view.

**Comment by MichaelCereda** [comment]
yes you can also use that, but i highly encourage you to create your own solution using the official _ScrollView_

**Comment by abellee** [comment]
If I clicked the InputField, error happened
![image](https://cloud.githubusercontent.com/assets/707615/16659639/96078a90-449d-11e6-8af6-bb9d3ccebce2.png)

maybe just like you said, I need to do it myself.

**Comment by MichaelCereda** [comment]
can you post a code sample, that error means nothing, it's just the event that is triggered by the focusaction

**Comment by abellee** [comment]
import React, { Component } from 'react';

    import {
        View,
        Text,
        ScrollView
    } from 'react-native';

    import {
        Form,
        Separator,
        InputField,
    } from "react-native-form-generator";

    import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'

    class ShirtOrder extends Component {

        state={
            formData: {}
        }

        handleFormFocus(event, reactNode){
           this.refs.scroll.scrollToFocusedInput(event, reactNode)
        }

        handleFormChange(formData){

        }

        render(){
            return (
                <KeyboardAwareScrollView
                    ref="scroll"
                >
                    <Form
                        ref="shirtOrder"
                        onFocus={ this.handleFormFocus.bind(this)}
                        onChange={this.handleFormChange.bind(this)}
                    >
                        <InputField
                            ref="ordernumnow"
                            label="orderNum" />

                    </Form>
                </KeyboardAwareScrollView>
            );
        }
    }
    export default ShirtOrder;

**Comment by abellee** [comment]
I found what's with this,
I've forgot to remove the code in handleFormFocus

**Comment by MichaelCereda** [comment]
;) if you want post a screenshot of your final form in action, i would love
to see it.
Have a nice day.

On Thu, Jul 7, 2016 at 5:56 PM abellee <notifications@github.com> wrote:

> I found what's with this,
> I've forgot to remove the code in handleFormFocus
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/MichaelCereda/react-native-form-generator/issues/22#issuecomment-231123742>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGjfgKm8LRREQB6oZJu3w1R6hUAC1TJks5qTSG_gaJpZM4JHJF7>
> .
>
-- 
Michael Cereda
http://michaelcereda.com
