### ISSUE TITLE
InputField lacks a setValue method on android

### ISSUE THREAD

**Issue by edy** [MichaelCereda/react-native-form-generator#24]
On iOS you can set value programmatically, but on Android a ReferenceError is raised because the method `setValue` is absent.

**Comment by MichaelCereda** [comment]
I'm going to fix it in a couple hours and release the update. Thank you

On Mon, Jul 11, 2016, 3:57 PM Eduard Baun <notifications@github.com> wrote:

> On iOS you can set value programmatically, but on Android a ReferenceError
> is raised because the method setValue is absent.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichaelCereda/react-native-form-generator/issues/24>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGjfoquXfzQiXlYwz2DMOHDhJmFt3PJks5qUkvBgaJpZM4JJY_K>
> .
>
-- 
Michael Cereda
http://michaelcereda.com

**Comment by MichaelCereda** [comment]
Fixed in 0.9.2
Thanks for your help
