### ISSUE TITLE
InputField: TextInput is cut off at the bottom if used with label

### ISSUE THREAD

**Issue by edy** [MichaelCereda/react-native-form-generator#25]
Tested with Android. Maybe this error is present on iOS too.

```
<InputField ref="hostname" label="Hostname" value={this.props.settings.hostname} placeholder="Hostname"/>
<InputField ref="path" label="Path" value={this.props.settings.path} placeholder="Path" />
```
![screenshot_20160711-155813](https://cloud.githubusercontent.com/assets/39267/16733191/d4036e6e-4780-11e6-8415-f925f3e69cce.png)

**Comment by MichaelCereda** [comment]
Fixed in 0.9.2 
thanks for your help! :)
