### ISSUE TITLE
Wrap PickerField in Modal

### ISSUE THREAD

**Issue by Shakarang** [MichaelCereda/react-native-form-generator#26]
Hey !

I've tried your example and I want to wrap a ```PickerField``` in the ```CustomModal```.

It works fine with ```DatePickerField``` but not with the ```PickerField```.

Here is my code

        <PickerField ref='height'
          label='Height (cm)'
          placeholder='100'
          prettyPrint={true}
          pickerWrapper={<CustomModal />}
          options={this.heightValues}
        />
      
        <DatePickerField ref='birthday'
          minimumDate={new Date('1/1/1900')}
          maximumDate={new Date()}
          placeholder='Birthday'
          mode='date'
          pickerWrapper={<CustomModal />}
        />

**Comment by MichaelCereda** [comment]
I'm adding it right now ;) 
sorry I have been so busy in the last weeks!

**Comment by Shakarang** [comment]
No problem, you saved me from a lot of work.

I'm also trying to bring weight management to my application. Is there a way to have multiple columns?

**Comment by MichaelCereda** [comment]
fixed in 0.9.3, you're good to go now.

I would suggest to create a custom field. It's very easy and you have unlimited flexibility.
