### ISSUE TITLE
Requiring unknown module "react-native-form-generator" in release build.

### ISSUE THREAD

**Issue by ganapativs** [MichaelCereda/react-native-form-generator#27]
I think it is because the main file is called index.ios.js?
Could you try to rename it index.js and update the main property of the package.json accordingly ?

More info here - https://github.com/maxs15/react-native-spinkit/issues/9#issuecomment-208566694

**Comment by ganapativs** [comment]
Created a pull request here with the working fix - https://github.com/MichaelCereda/react-native-form-generator/pull/28

**Comment by MichaelCereda** [comment]
Sorry for the latency, I can't reproduce the problem.
I'm going to check it and merge the PR.
Thank you :)

**Comment by ganapativs** [comment]
Cool, it happened to me in Android release build with "react": "15.0.2", "react-native": "0.26.2". thanks.

**Comment by bgnlordhelmut** [comment]
Also happening to me as well, "react": "^0.14.8", "react-native": "^0.24.0"

**Comment by MichaelCereda** [comment]
I apologize for the latency... i fixed everything and i'm going to publish the new update.
thanks
