### ISSUE TITLE
SetValue() on PickerField

### ISSUE THREAD

**Issue by Shakarang** [MichaelCereda/react-native-form-generator#29]
Hey !

How can I use setValue() on Picker row?

The code in "normal" fields works but not with Picker.

```
this.refs.registrationForm.refs.password.setValue(""); // OK 
this.refs.registrationForm.refs.height.setValue(store.user.user.height); // NOT OK
```

**Comment by MichaelCereda** [comment]
Hello, I'm releasing an update.
I think that it will be ready in few hours.
Thank you

**Comment by MichaelCereda** [comment]
It should be fixed now. 0.9.4
Have a nice day

**Comment by Shakarang** [comment]
Thank you ! It works like a charm !
