### ISSUE TITLE
PickerField not responding to onFocus or onPress events

### ISSUE THREAD

**Issue by bgnlordhelmut** [MichaelCereda/react-native-form-generator#32]
Using the following example:

<PickerField ref='state'
        label='State'
        onFocus={() => {console.log("test onFocus")}}
        onPress={() => {console.log("onPress of state picker");}}
        options={stateOptions}/>

These events do not seem to be firing.

**Comment by MichaelCereda** [comment]
I'm checking the code and I'm going to fix it today. 
I think that the onfocus it's not very appropriate. 
I'll add onPress

**Comment by bgnlordhelmut** [comment]
Good point on the onFocus, agreed on that point.

Thanks for adding Michael!

**Comment by MichaelCereda** [comment]
added in v0.9.6
