### ISSUE TITLE
Default value not stored in formData unless field was changed.

### ISSUE THREAD

**Issue by Rdebokx** [MichaelCereda/react-native-form-generator#34]
Using the code below, this.state.formData.gender remains"undefined", unless the picker was set to a different value (and back in case you actually want the default value). I think the desired behavior would be that this.state.formData.gender is set to "M" in this situation, even when the user does not change the picker value.

```javascript
handleFormChange(formData){
  this.setState({formData:formData})
}

render(){
  return(<ScrollView keyboardShouldPersistTaps={true} style={{marginTop: h.scale(50), paddingLeft:10,paddingRight:10, height:200}}>
  <Form
    ref='paymentForm'
    onChange={this.handleFormChange.bind(this)}>

    <PickerField
      ref='gender'
      label='Gender'
      value='M'
      options={M: "Male", F: "Female"}/>
    </Form>
  </ScrollView>);
}

```

**Comment by MichaelCereda** [comment]
check the example ... it works perfectly
