### ISSUE TITLE
make .togglePicker function public

### ISSUE THREAD

**Issue by Rdebokx** [MichaelCereda/react-native-form-generator#35]
As part of the user experience, I want to be able to close picker modals programmatically when the user selects the next field in the form.
It seems that inside the PickerComponent, the _togglePicker function (https://github.com/MichaelCereda/react-native-form-generator/blob/master/src/lib/PickerComponent.ios.js#L53)  does exactly this, but it's not accessible from outside the class.

Would it be possible to make this method publicly accessible?

**Comment by MichaelCereda** [comment]
mm... it's possible but it's actually an antipattern.
the react-way should be using the onChange function to set a prop on the component.

**Comment by MichaelCereda** [comment]
If you check the example you will notice that is possible to change the behavior of one field based on the value of another.
