### ISSUE TITLE
dateTimeFormat

### ISSUE THREAD

**Issue by matthewwoop** [MichaelCereda/react-native-form-generator#36]
How are we to use the dateTimeFormat prop for TimePickerField and DatePickerField? For example, I only want the time to display as '5:30 PM', not '5:30:22 PM. Essentially, I don't want to seconds to show up, as they're kind of unnecessary for my case.

Any help would be greatly appreciated.

**Comment by MichaelCereda** [comment]
Hello, first of all. thanks for using react-native-form-generator.

Creating a dateTimeFormat function is very easy... let me explain

the default is the following [DatePickerComponent.ios.js#L123-L140](https://github.com/MichaelCereda/react-native-form-generator/blob/master/src/lib/DatePickerComponent.ios.js#L123-L140) (for ios), if you want to change it just pass a _dateTimeFormat_ prop like the following

```javascript
dateTimeFormat: (date, mode)=>{
    if(!date) return "";
    let value=date.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
   return value;
  }
};
```

more info here http://stackoverflow.com/questions/17913681/how-do-i-use-tolocaletimestring-without-displaying-seconds

have a nice day

**Comment by matthewwoop** [comment]
Awesome, very helpful. Thanks for all the hard work you've put into the project! Loved using it so far
