### ISSUE TITLE
Not possible to completely style DatePickerField

### ISSUE THREAD

**Issue by braco** [MichaelCereda/react-native-form-generator#38]
Looks like it's missing a style prop or two:

https://github.com/MichaelCereda/react-native-form-generator/blob/master/src/lib/DatePickerComponent.ios.js#L93

https://github.com/MichaelCereda/react-native-form-generator/blob/master/src/lib/DatePickerComponent.ios.js#L95

so users can't currently style the DatePicker value field exactly as an input field looks.

**Comment by MichaelCereda** [comment]
fixed in 0.9.7.
