### ISSUE TITLE
KeyboardType value of empty string or 'email' causes shaking

### ISSUE THREAD

**Issue by davidpaulmcintyre** [MichaelCereda/react-native-form-generator#42]
the markdown doc states that keyboardType can be set to '' or 'email'.  Either value causes form to shake and be unusable.  The problem can be fixed by not having the attribute present at all, or by setting it to 'email-address'.

**Comment by MichaelCereda** [comment]
I'll run some tests and fix it. thank you

**Comment by davidpaulmcintyre** [comment]
thanks for getting back to me so quick.  after playing around w/ it some more, i'm less certain that it has to do w/ keyboardType, or at least it's not solely KT.  i can also repro the issue if i remove the keyboardType attribute and merely have a initial value set to either empty string or a valid email address.  
this combination of attributes seems to work ok:
keyboardType='email-address' value={' '}

**Comment by MichaelCereda** [comment]
are you on android or ios? which version of RN?

**Comment by davidpaulmcintyre** [comment]
iOS.  at first i thought the vibrating issue might just be an artifact of the simulator, but i experience it on my device as well.
version of RN is 0.29.1

**Comment by MichaelCereda** [comment]
I updated the docs and the example... I'm trying to reproduce the problem but without any luck.
I'll live this issue open while I'm investigating. 
Thank you.

**Comment by davidpaulmcintyre** [comment]
just ran across this at Direct Manipulation – React Native | A framework for building native apps using React that might explain the issue.  see the section under "avoiding conflicts w/ the render fn"
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Direct Manipulation – React Native | A framework for building native apps u...
 A framework for building native apps using React  |   |

  |

  |
