### ISSUE TITLE
datepickerfield invalidDate

### ISSUE THREAD

**Issue by ChangJoo-Park** [MichaelCereda/react-native-form-generator#5]
Hello,
How to use datepickerfield? everytime I get invalidDate when I tried to set value.

example :
```
    value={new Date()} // invalidDate
    value={moment()} // invliadDate
```
please help me

**Comment by MichaelCereda** [comment]
Hello, update the library at the last version 0.6.12 and use datepicker like this
`
<DatePickerField ref='birthday'
                    minimumDate={new Date('1/1/1900')}
date={new Date()}
                    maximumDate={new Date()} mode='date' placeholder='Birthday'/>
`

**Comment by ChangJoo-Park** [comment]
@MichaelCereda Thanks I was confused value and date
