### ISSUE TITLE
commented out KeyboardAwareScrollView

### ISSUE THREAD

**Issue by Paul-Todd** [MichaelCereda/react-native-form-generator#59]
Is there a reason that KeyboardAwareScrollView is commented out in the index.js file?

This means i am unable to use it (easily) in projects.

**Comment by MichaelCereda** [comment]
Yes.. it's commented out because it uses deprecated functions of react native, I'm working to restore it's behavior.
In the mean time you an use the KeyboardAwareScrollView package on npm, it should integrate seamlessy
