### ISSUE TITLE
Help Text

### ISSUE THREAD

**Issue by timbielawski** [MichaelCereda/react-native-form-generator#63]
Unable to style help text would be nice to send style through props?

**Comment by timbielawski** [comment]
Oh I see there is a helpTextComponent will try that

**Comment by MichaelCereda** [comment]
Yes. you can try the component for advanced styling.
I'm about to merge a PR that adds HelpText styling too

**Comment by timbielawski** [comment]
hi,

yeah I did that PR :)

But since I got you is the best way to set form data via setValue from
props?

thanks

**Comment by MichaelCereda** [comment]
Yes :) 
I noticed right after I commented your Issue.
I apologize but I have been very busy in the last weeks.

You can setup a value in a field using the _value_ prop of using refs (eg. this.refs.myform.refs.myfield.setValue('test')).

**Comment by timbielawski** [comment]
Ok thanks and thanks for the lib :)
