### ISSUE TITLE
Validate one field at a time

### ISSUE THREAD

**Issue by compojoom** [MichaelCereda/react-native-form-generator#67]
Hi!
Awesome component! I had some issues with styling on android, but other than that it was a pretty straight forward to create form. I have one issue though. When I have several fields that need validation triggering an error on any one field will show the helptext for all the fields. 
Is there a way to show the error only for the specified field and to trigger the validation on the whole form when saving the form?

**Comment by compojoom** [comment]
Actually, I've looked at the code a little more. IN the inputComponent you are doing this.validate(props.value); So basically when I create the form you always call this.validate on the passed value. And since nearly all my fields have a required requirement my form fills up with all the help text for each field. If I comment out this line, then the form behaves as expected -> whenever I click on an element and the specified validation rule is not met, the component shows the helptext. 

Why are we doing the initial validate in the constructor?

How do I trigger a validate on the whole form?

**Comment by MichaelCereda** [comment]
The validation on the whole form can easly be done just at the Form.onChange event.
I trigger a validate on constructor just to check if the value is valid when the field is mounted.
