### ISSUE TITLE
Missing react-native-vector-icons dependency in package.json

### ISSUE THREAD

**Issue by 5amfung** [MichaelCereda/react-native-form-generator#7]
LinkField has reference to ```react-native-vector-icons``` but it's not in package.json.  Therefore I got
```Unable to resolve module react-native-vector-icons/Ionicons...``` error.

**Comment by MichaelCereda** [comment]
Yes it's missing by now because it's required just for certain fields.
I'm planning to remove the dependency entirely.
Any thoughts?

**Comment by 5amfung** [comment]
Can we use ```this.props.children``` within ```render()``` of ```LinkField``` to let user pass in the ```<Icon>``` as a child so that we can remove the dependency of ```react-native-vector-icon```?

Replace https://github.com/MichaelCereda/react-native-form-generator/blob/master/fields/LinkField.js#L36-L38 with
```
  {this.props.children}
```

And this is how to add a right arrow to the link field:
```
<LinkField>
  <Icon name='ios-arrow-right'/>
</LinkField>
```

**Comment by MichaelCereda** [comment]
Actually i was thinking a something more like this (to improve flexibility and allow developers to create their custom fields):

```
   <LinkField
      iconRight={<Icon name='ios-arrow-right'/>}
      label="Sample text"
   />
```

that should avoid problems... i'm preparing a new release right now and including also android support

**Comment by 5amfung** [comment]
This is great. Looking forward to new release.

**Comment by MichaelCereda** [comment]
i'm going to release the new version in minutes.
Android support will be included after a lot of tests (i'm developing a cross browser app).

**Comment by MichaelCereda** [comment]
@5amfung, please check my release, added some other examples in the README file
