### ISSUE TITLE
How to use datepicker for only date not time?

### ISSUE THREAD

**Issue by rukor** [MichaelCereda/react-native-form-generator#77]
Is there a way to do this?

**Comment by rukor** [comment]
Found out the mode prop

**Comment by michaelbenker** [comment]
I have the same problem? What means "mode prop"? Thanks...

**Comment by michaelbenker** [comment]
got it...
<DatePickerField ref='birthday'
                                 **mode='date'**
                                 minimumDate={new Date('1/1/1900')}
                                 maximumDate={new Date()}
                                 placeholder='Birthday'/>

prop "mode" is not in the documentation, but works
