### ISSUE TITLE
helpText not shown

### ISSUE THREAD

**Issue by 5amfung** [MichaelCereda/react-native-form-generator#9]
Not sure why, but helpText is not shown for ```<LinkField>```.  It only works for ```<SwitchField>```.
```
 <Form ref='logInForm' label="Information" onChange={this._handleFormChange.bind(this)}>
    <Separator label='Please read'/>
    <LinkField label='Terms and Conditions'
                               onPress={this._openTermsAndConditions.bind(this)}
                               helpText='By signing up, I agree to the terms and conditions.'/>
</Form>
```

**Comment by MichaelCereda** [comment]
I'll check this tonight ... very strange

**Comment by MichaelCereda** [comment]
I'm going to release a new version with the fix (that will include also https://github.com/MichaelCereda/react-native-form-generator/issues/6) .
Thanks for your efforts, i really appreciate.

**Comment by MichaelCereda** [comment]
@5amfung please check the new version, i have been very busy in these days ...
